  
# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: dockerhub and deployment

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 11
    - run: mvn -B package --file pom.xml
    - run: mkdir jars && cp target/*.jar jars
    - uses: actions/upload-artifact@v1
      with:
        name: Package
        path: jars
      
  docker-build:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/download-artifact@v1
      with:
          name: Package
          path: target/
    - name: Kaniko build
      uses: outillage/kaniko-action@master
      with:
        image: pierreros/carryon-backend
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
        
  k8s-deployment:
    needs: [docker-build]
    name: deploy to cluster
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: deploy to cluster
      uses: steebchen/kubectl@master
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
      with:
        args: replace --force ./k8s/deployment.yml
